version: 2

sources:
    - name: staging
      database: afro-de-376122
      schema: afrodbt
      # schema: dbt

      tables:
        - name: dbt-green
        - name: dbt-yellow
        - name: dbt-fhv
